version: "3.5"

services:
  app:
    build: .
    ports:
      - target: 8080
        published: 8080
    volumes:
      - type: volume
        source: simpleapp-data
        target: /src/data

  redis:
    image: "redis"

volumes:
  simpleapp-data:
